# MYSQL DB PROPERTIES
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/test    # USE TO CONNECT LOCALLY
    url: jdbc:mysql://mysql:3306/test         # USE TO CONNECT TO CONTAINER
    username: testuser
    password: testuser@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # POSTGRES DB PROPERTIES
  # spring:
  #  datasource:
  #    url: jdbc:postgresql://postgres/testdb
  #    username: postgres
  #    password: admin
  #    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true