version: "3"

services:
  # account service container
  accounts-service:
    container_name: accounts-service
    image: accounts-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - mysql

  # mysql container
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser@123
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql_data: null

networks:
  backend: null
