apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\SUBHANKAR-WS\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ./docker-compose-prod.yml -o ./k8s
    kompose.service.type: loadbalancer
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-boot-k8s-tcp
  name: spring-boot-k8s-tcp
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: spring-boot-k8s
  type: LoadBalancer
status:
  loadBalancer: {}
