apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\SUBHANKAR-WS\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ./docker-compose-prod.yml -o ./k8s
    kompose.service.type: loadbalancer
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-boot-k8s
  name: spring-boot-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring-boot-k8s
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\SUBHANKAR-WS\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ./docker-compose-prod.yml -o ./k8s
        kompose.service.type: loadbalancer
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-boot-kubernetes-backend: "true"
        io.kompose.service: spring-boot-k8s
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: subhankardas831/spring-boot-k8s:latest
          name: spring-boot-k8s
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
